version: "3.7"

services:

  app:
    build:
      context: .
      target: development
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kairos
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: kairos_manager

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
