version: "3"

services:

  app:
    image: viniosilva/kairos-manager:dev
    environment:
      DB_HOST: db
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000

  db:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kairos
      POSTGRES_PASSWORD: kairos_manager
      POSTGRES_DB: kairos_manager

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
